python adjust.py -seq 33 -exp 4
python adjust.py -seq 34 -exp 1
python adjust.py -seq 34 -exp 2
python adjust.py -seq 34 -exp 3
python adjust.py -seq 34 -exp 4
python adjust.py -seq 35 -exp 1
python adjust.py -seq 35 -exp 2
python adjust.py -seq 35 -exp 3
python adjust.py -seq 35 -exp 4
python adjust.py -seq 36 -exp 1
python adjust.py -seq 36 -exp 2
python adjust.py -seq 36 -exp 3
python adjust.py -seq 36 -exp 4
python adjust.py -seq 37 -exp 1
python adjust.py -seq 37 -exp 2
python adjust.py -seq 37 -exp 3
python adjust.py -seq 37 -exp 4
python adjust.py -seq 38 -exp 1
python adjust.py -seq 38 -exp 2
python adjust.py -seq 38 -exp 3
python adjust.py -seq 38 -exp 4
python adjust.py -seq 39 -exp 1
python adjust.py -seq 39 -exp 2
python adjust.py -seq 39 -exp 3
python adjust.py -seq 39 -exp 4
python adjust.py -seq 44 -exp 4
python adjust.py -seq 45 -exp 1
python adjust.py -seq 45 -exp 2
python adjust.py -seq 45 -exp 3
python adjust.py -seq 45 -exp 4
python adjust.py -seq 46 -exp 1
python adjust.py -seq 46 -exp 2
python adjust.py -seq 46 -exp 3
python adjust.py -seq 46 -exp 4
python adjust.py -seq 47 -exp 1
python adjust.py -seq 47 -exp 2
python adjust.py -seq 47 -exp 3
python adjust.py -seq 47 -exp 4
python adjust.py -seq 48 -exp 1
python adjust.py -seq 48 -exp 2
python adjust.py -seq 48 -exp 3
python adjust.py -seq 48 -exp 4
python adjust.py -seq 49 -exp 1
python adjust.py -seq 49 -exp 2
python adjust.py -seq 49 -exp 3
python adjust.py -seq 49 -exp 4

