python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 1
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 2
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 3
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 4
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 5
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 6
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 7
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 8
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 9
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 10
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 11
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 12
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 13
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 14
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 15
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 16
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 17
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 18
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 19