python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 40
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 41
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 42
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 43
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 44
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 45
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 46
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 47
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 48
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 49
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 50
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 51
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 52
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 53
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 54
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 55
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 56
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 57
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 58
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 59