python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 20
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 21
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 22
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 23
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 24
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 25
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 26
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 27
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 28
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 29
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 30
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 31
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 32
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 33
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 34
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 35
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 36
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 37
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 38
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 39