python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 60
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 61
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 62
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 63
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 64
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 65
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 66
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 67
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 68
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 69
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 70
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 71
python /gpfs/slac/kipac/fs1/u/dthomas5/science/StarTrailPipeline/scripts/registration/calculateCorrections.py -seq 72